update amend logic to honor --no-verify

diff --git a/.git-template/hooks/prepare-commit-msg b/.git-template/hooks/prepare-commit-msg
--- a/.git-template/hooks/prepare-commit-msg
+++ b/.git-template/hooks/prepare-commit-msg
@@ -22,15 +22,19 @@ if [ "$3" == HEAD ] ; then
     exit 1
   fi
 
-  # prevent amending commit found in other branches
-  branches=$(
-    git branch -a --contains $(git log -1 --pretty=tformat:%h) |
-    perl -ne "print unless /\b($(git brname))\b/"
-  )
-  if [ -n "$branches" ] ; then
-    echo "abort: the following branches contain the commit to be amended:"
-    for b in $branches ; do echo -e "  $b" ; done
-    exit 1
+  # allow if --no-verify was supplied (git ignores for prepare-commit-msg)
+  no_verify=$(ps -ocommand= -p $PPID | grep -e '--no-verify');
+  if [ -z "$no_verify" ] ; then
+    # prevent amending commit found in other branches
+    branches=$(
+      git branch -a --contains $(git log -1 --pretty=tformat:%h) |
+      perl -ne "print unless /\b($(git brname)|qa-test)\b/"
+    )
+    if [ -n "$branches" ] ; then
+      echo "abort: the following branches contain the commit to be amended:"
+      for b in $branches ; do echo -e "  $b" ; done
+      exit 1
+    fi
   fi
 
 # Non-amend, look for ticket number prefix on the branch name, and if found,
